FROM python:3-onbuild
EXPOSE 5000
ARG dir 

COPY . /tmp
WORKDIR /tmp
RUN python3 -m venv venv
RUN . venv/bin/activate
RUN pip install -e .
RUN pip install '.[test]' 
RUN coverage run -m pytest > /tmp/test.txt
ENTRYPOINT coverage report
