# This is a basic workflow to help you get started with Actions

name: CI

env:
  PROJECT_NAME: "web_calculator"
  
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Deploy:
    runs-on: [ubuntu-latest]
    steps:
     - uses: actions/checkout@v2

     - name: drop previous container
       run: |
        touch  ~/.ssh/known_hosts
        ssh-keygen -R ${{ secrets.REMOTE_HOST }} -f ~/.ssh/known_hosts
        echo ${{ secrets.REMOTE_PASS}} | ssh ${{ secrets.REMOTE_PS }}@${{ secrets.REMOTE_HOST }} 'docker kill ${{ secrets.DOCKER_LOGIN }}/$PROJECT_NAME:latest' 
     - name: up container
       run: echo ${{ secrets.REMOTE_PASS}} | ssh ${{ secrets.REMOTE_PS }}@${{ secrets.REMOTE_HOST }} 'docker run -p 5000:5000 ${{ secrets.DOCKER_LOGIN }}/$PROJECT_NAME:latest' 
  
  End-to-end:
    runs-on: [ubuntu-latest]
    steps:
     - uses: actions/checkout@v2
     - name: check by selenium
       run: echo "selenium"

