# This is a basic workflow to help you get started with Actions

name: CI

env:
  PROJECT_NAME: "web_calculator"
  
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  codeStyle:
    # The type of runner that the job will run on
    runs-on: [ubuntu-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Python Style Checker 
      uses: andymckay/pycodestyle-action@0.1.3
      continue-on-error: true
    
  Test:
    runs-on: [ubuntu-latest]
    needs: [codeStyle]
    
    steps:
      - uses: actions/checkout@v2
      - name: build test container
        run: sudo docker build -t $PROJECT_NAME:_Test -f Dockerfile_for_tests . --build-arg .
      - name: Run testing
        run:  docker run -v /tmp:dir/docker $PROJECT_NAME:_Test
      - name: ls
        run: ls /tmp
      - uses: actions/upload-artifact@v2
        with:
          name: test
          path: /tmp/unit_tests.txt

  Push_to_docker:
   runs-on: [ubuntu-latest]
   needs: [Test, codeStyle] 
   steps:
     - uses: actions/checkout@v2

     - name: Docker build
       run: docker build -t ${{ secrets.DOCKER_LOGIN }}/$PROJECT_NAME:latest .
            
     - name: Upload to docker hub 
       run: |
            docker login --username=${{ secrets.DOCKER_LOGIN }} --password=${{ secrets.DOCKER_PASSWORD }}
            docker push ${{ secrets.DOCKER_LOGIN }}/$PROJECT_NAME:latest
